version: '3.7'

services:
  mariadb:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    build: 
      context: ./mariadb
    restart: always
    ports:
      - "3306:3306"
    
  clickhouse:
    restart: always
    image: yandex/clickhouse-server
    ulimits: 
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9000:9000"
    depends_on:
      - mariadb